Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyCv.Models.Entity;
using MyCv.Repositories;
namespace MyCv.Controllers
{
    public class AboutController : Controller
    {
        GenericRepository<About> repos = new GenericRepository<About>();
        // GET: Interest
        [HttpGet]
        public ActionResult Index()
        {
            var abt = repos.List();
            return View(abt);
        }
        
         [HttpPost]
        public ActionResult Index(About p)
        {
            About ab = repos.Find(x => x.ID == 1);
            ab.Name = p.Name;
            ab.Surname = p.Surname;
            ab.Phone = p.Phone;
            ab.Image = p.Image;
            ab.Adress = p.Adress;
            ab.Email = p.Email;
            ab.Explanation = p.Explanation;

            repos.TUpdate(ab);
            return RedirectToAction("Index");
        }
    }
}

Controllers/ContactController.cs
using MyCv.Models.Entity;
using MyCv.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyCv.Controllers
{
    public class ContactController : Controller
    {

        GenericRepository<Contact> repos = new GenericRepository<Contact>();

        // GET: Contact
        public ActionResult Index()
        {
            var messages = repos.List();
            return View(messages);
        }
    }
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Project Add</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/AdminLTE-3.1.0/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/AdminLTE-3.1.0/dist/css/adminlte.min.css">
</head>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Navbar -->
        
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="/Default/Index/" class="brand-link">
                <img src="/AdminLTE-3.1.0/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">GO WEBSITE</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="/AdminLTE-3.1.0/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">Admin Page</a>
                    </div>
                </div>
                
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library -->
                        <li class="nav-item">
                            <a href="/About/Index" class="nav-link">
                                <i class="nav-icon fas fa-user"></i>
                                <p>
                                    About

                                </p>
                            </a>

                        </li>
                        <li class="nav-item">
                            <a href="/Education/Index" class="nav-link">
                                <i class="nav-icon fas fa-university"></i>
                                <p>
                                    Educations

                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/Experience/Index" class="nav-link">
                                <i class="nav-icon fas fa-user-edit"></i>
                                <p>
                                    Experiences

                                </p>
                            </a>

                        </li>
                        <li class="nav-item">
                            <a href="/Interest/Index" class="nav-link">
                                <i class="nav-icon fas fa-theater-masks"></i>
                                <p>
                                    Interests
                            
                                </p>
                            </a>

                        </li>
                        <li class="nav-item">
                            <a href="/Skills/Index" class="nav-link">
                                <i class="nav-icon fab fa-asymmetrik"></i>
                                <p>
                                    Skills
                                </p>
                            </a>

                        </li>
                        <li class="nav-item">
                            <a href="/Contact/Index/" class="nav-link">
                                <i class="nav-icon fas fa-address-card"></i>
                                <p>
                                    Contacts

                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/SocialMedia/Index" class="nav-link">
                                <i class="nav-icon fas fa-hashtag"></i>
                                <p>
                                    Social Media
                                </p>
                            </a>

                        </li>
                        <li class="nav-item">
                            <a href="/Login/Logout" class="nav-link">
                                <i class="nav-icon fas fa-sign-out-alt"></i>
                                <p>
                                    Logout
                                </p>
                            </a>

                        </li>
                    </ul>
                </nav>
            </div>
            <!-- /.sidebar -->
        </aside>

        <div class="content-wrapper">
              <section class="content">
                <div class="row">
                    <div class="col-md-12">
                      @RenderBody()
                    </div>
                 </div>
             </section>
            <!-- /.content -->
        </div>
               
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="/AdminLTE-3.1.0/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="/AdminLTE-3.1.0/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/AdminLTE-3.1.0/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/AdminLTE-3.1.0/dist/js/demo.js"></script>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASP.NET Uygulamam</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Uygulama adı", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Giriş Sayfası", "Index", "Home")</li>
                    <li>@Html.ActionLink("Hakkında", "About", "Home")</li>
                    <li>@Html.ActionLink("Kişi", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ASP.NET Uygulamam</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>